version: '3.3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data  
    environment:
      POSTGRES_DB: fc-monolito
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    networks:
      - go-docker-net  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5  

  api:
      image: go-docker-image-debug:latest
      container_name: 'go-docker_api-debug'
      ports:
          - '4000:4000'
          - '8080:8080'
      volumes:
          - ./:/go/src/app/
          - ./go.mod:/go/src/app/go.mod
      restart: always
      networks:
          - go-docker-net    
networks:
  go-docker-net:
    driver: bridge
volumes:
  db-data:
