version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: fc-monolito
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
      image: go-docker-image:latest #Our go-docker image here
      container_name: 'go-docker_api'
      ports:
          - '8080:8080'
      volumes:
          - ./:/go/src/app/
          - ./go.mod:/go/src/app/go.mod
      restart: always
      networks:
          - go-docker-net    
networks:
  go-docker-net:
    driver: bridge
volumes:
  db-data:
