version: '3.3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data  
    environment:
      POSTGRES_DB: fc-monolito
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    networks:
      - go-docker-net  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5  

  migrate:
    image: migrate/migrate
    networks:
      - go-docker-net  
    volumes:
      - ./migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:123456@db:5432/fc-monolito?sslmode=disable",
      ]
    command: ["up"]
    depends_on:
      - db
    restart: on-failure

  api:
      image: go-docker-image:latest
      container_name: 'go-docker_api'
      ports:
          - '8080:8080'
      volumes:
          - ./:/go/src/app/
          - ./go.mod:/go/src/app/go.mod
      restart: always
      networks:
          - go-docker-net    
networks:
  go-docker-net:
    driver: bridge
volumes:
  db-data:
