// Code generated by mockery v1.0.0. DO NOT EDIT.

package repomocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import repository "github.com/MarcoBuarque/monolito/internal/modules/product_adm/repository"

// IProductRepository is an autogenerated mock type for the IProductRepository type
type IProductRepository struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, data
func (_m *IProductRepository) Add(ctx context.Context, data repository.ProductData) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ProductData) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, id
func (_m *IProductRepository) Find(ctx context.Context, id string) (repository.ProductData, error) {
	ret := _m.Called(ctx, id)

	var r0 repository.ProductData
	if rf, ok := ret.Get(0).(func(context.Context, string) repository.ProductData); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(repository.ProductData)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
