// Code generated by mockery v1.0.0. DO NOT EDIT.

package usecasemocks

import context "context"
import mock "github.com/stretchr/testify/mock"

// ICheckStockUseCase is an autogenerated mock type for the ICheckStockUseCase type
type ICheckStockUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, id
func (_m *ICheckStockUseCase) Execute(ctx context.Context, id string) (int32, error) {
	ret := _m.Called(ctx, id)

	var r0 int32
	if rf, ok := ret.Get(0).(func(context.Context, string) int32); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
