// Code generated by mockery v1.0.0. DO NOT EDIT.

package usecasemocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import repository "github.com/MarcoBuarque/fc-monolito-golang/internal/modules/product_adm/repository"

// ICreateProductUseCase is an autogenerated mock type for the ICreateProductUseCase type
type ICreateProductUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, data
func (_m *ICreateProductUseCase) Execute(ctx context.Context, data repository.Product) (repository.Product, error) {
	ret := _m.Called(ctx, data)

	var r0 repository.Product
	if rf, ok := ret.Get(0).(func(context.Context, repository.Product) repository.Product); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(repository.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, repository.Product) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
