// Code generated by mockery v1.0.0. DO NOT EDIT.

package usecasemocks

import context "context"

import mock "github.com/stretchr/testify/mock"
import repository "github.com/MarcoBuarque/fc-monolito-golang/internal/modules/client_adm/repository"

// ICreateClientUseCase is an autogenerated mock type for the ICreateClientUseCase type
type ICreateClientUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, data
func (_m *ICreateClientUseCase) Execute(ctx context.Context, data repository.Client) (repository.Client, error) {
	ret := _m.Called(ctx, data)

	var r0 repository.Client
	if rf, ok := ret.Get(0).(func(context.Context, repository.Client) repository.Client); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(repository.Client)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, repository.Client) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
