// Code generated by mockery v1.0.0. DO NOT EDIT.

package usecasemocks

import context "context"

import mock "github.com/stretchr/testify/mock"
import repository "github.com/MarcoBuarque/monolito/internal/modules/client_adm/repository"

// IFindClientUseCase is an autogenerated mock type for the IFindClientUseCase type
type IFindClientUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, clientID
func (_m *IFindClientUseCase) Execute(ctx context.Context, clientID string) (repository.Client, error) {
	ret := _m.Called(ctx, clientID)

	var r0 repository.Client
	if rf, ok := ret.Get(0).(func(context.Context, string) repository.Client); ok {
		r0 = rf(ctx, clientID)
	} else {
		r0 = ret.Get(0).(repository.Client)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
