// Code generated by mockery v1.0.0. DO NOT EDIT.

package repomocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import repository "github.com/MarcoBuarque/monolito/internal/modules/checkout/repository"

// ICheckoutRepository is an autogenerated mock type for the ICheckoutRepository type
type ICheckoutRepository struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, order
func (_m *ICheckoutRepository) CreateOrder(ctx context.Context, order repository.Order) error {
	ret := _m.Called(ctx, order)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOrder provides a mock function with given fields: ctx, orderID
func (_m *ICheckoutRepository) GetOrder(ctx context.Context, orderID string) (repository.Order, error) {
	ret := _m.Called(ctx, orderID)

	var r0 repository.Order
	if rf, ok := ret.Get(0).(func(context.Context, string) repository.Order); ok {
		r0 = rf(ctx, orderID)
	} else {
		r0 = ret.Get(0).(repository.Order)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
