// Code generated by mockery v1.0.0. DO NOT EDIT.

package usecasemocks

import context "context"

import mock "github.com/stretchr/testify/mock"
import repository "github.com/MarcoBuarque/monolito/internal/modules/store_catalog/repository"

// IFindAllProductsUseCase is an autogenerated mock type for the IFindAllProductsUseCase type
type IFindAllProductsUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx
func (_m *IFindAllProductsUseCase) Execute(ctx context.Context) ([]repository.ProductData, error) {
	ret := _m.Called(ctx)

	var r0 []repository.ProductData
	if rf, ok := ret.Get(0).(func(context.Context) []repository.ProductData); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ProductData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
