// Code generated by mockery v1.0.0. DO NOT EDIT.

package usecasemocks

import context "context"

import mock "github.com/stretchr/testify/mock"
import repository "github.com/MarcoBuarque/fc-monolito-golang/internal/modules/store_catalog/repository"

// IGetProductUseCase is an autogenerated mock type for the IGetProductUseCase type
type IGetProductUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, productID
func (_m *IGetProductUseCase) Execute(ctx context.Context, productID string) (repository.ProductCatalog, error) {
	ret := _m.Called(ctx, productID)

	var r0 repository.ProductCatalog
	if rf, ok := ret.Get(0).(func(context.Context, string) repository.ProductCatalog); ok {
		r0 = rf(ctx, productID)
	} else {
		r0 = ret.Get(0).(repository.ProductCatalog)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
