// Code generated by mockery v1.0.0. DO NOT EDIT.

package usecasemocks

import context "context"

import mock "github.com/stretchr/testify/mock"
import repository "github.com/MarcoBuarque/monolito/internal/modules/store_catalog/repository"

// IListProductsUseCase is an autogenerated mock type for the IListProductsUseCase type
type IListProductsUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx
func (_m *IListProductsUseCase) Execute(ctx context.Context) ([]repository.ProductCatalog, error) {
	ret := _m.Called(ctx)

	var r0 []repository.ProductCatalog
	if rf, ok := ret.Get(0).(func(context.Context) []repository.ProductCatalog); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ProductCatalog)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
