// Code generated by mockery v1.0.0. DO NOT EDIT.

package usecasemocks

import context "context"
import mock "github.com/stretchr/testify/mock"

// IUpdateSalesPriceUseCase is an autogenerated mock type for the IUpdateSalesPriceUseCase type
type IUpdateSalesPriceUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, productID, price
func (_m *IUpdateSalesPriceUseCase) Execute(ctx context.Context, productID string, price float64) error {
	ret := _m.Called(ctx, productID, price)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64) error); ok {
		r0 = rf(ctx, productID, price)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
